name: Project 01 actual 16S outcome

on:
  push:
    paths:
      - '.github/workflows/16s-actual-outcome.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo 'runner test passed'